import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-8 ml-5 mt-5">
          <div>
            <Link href="/rendering/SSG">SSG</Link>
          </div>
          <div>
            <Link href="/rendering/ISR">ISR</Link>
          </div>
          <div>
            <Link href="/rendering/SSR">SSR</Link>
          </div>
          <div>
            <Link href="/rendering/CSR">CSR</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
